[build]
  command = "prisma generate && node scripts/db-push.js && next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["node_modules/.prisma/client/**", "prisma/schema.prisma"]
